### ISSUE TITLE
Uygulamada döviz bilgisi

### ISSUE THREAD

**Issue by Andromeda606** [ozgurg/vergihesaplayici.com#108]
Vue.js bilmediğim için detaylı inceleyemedim, Döviz kurunu nasıl çekiyorsunuz?

**Comment by ozgurg** [comment]
Vue.js ile bir bağlantısı yok.
Şu API'yı kullanıyorum: https://exchangeratesapi.io/

**Comment by Andromeda606** [comment]
adamsın
