### ISSUE TITLE
Öneri

### ISSUE THREAD

**Issue by vural2123** [ozgurg/vergihesaplayici.com#285]
Hocam emeğinize sağlık, backend geliştirmeyi düşünüyor musunuz?

**Comment by ozgurg** [comment]
Teşekkür ederim. Eğer gelecekte yeni eklemeler backend geliştirmemi gerektirirse elbette geliştiririm; ancak şu an Firebase kullandığım için sorunu Firebase ile çözebiliyorsam ilk tercihim o olur.
