### ISSUE TITLE
döviz verilerini bu linkten alsan daha iyi olur

### ISSUE THREAD

**Issue by mrcbrbn5361** [ozgurg/vergihesaplayici.com#301]
`[https://freecurrencyapi.com/](url)`

**Comment by ozgurg** [comment]
Öneri için teşekkür ederim. Bu API'n şu anda kullanılana göre neden daha iyi olacağını düşünüyorsun?

Açıkçası ücretsiz de olsa bir üyelik ve bir API key ile kullanılan bir sağlayıcıya sıcak bakmıyorum gerekmedikçe. Ancak daha da önemlisi freecurrencyapi.com'un aylık ücretsiz 5.000 istek sınırı vergihesaplayici.com'un yoğun olmadığı zamanlardaki kullanımı için bile yetersiz.

**Comment by ozgurg** [comment]
Kalabalık yapmaması için şuradan devam etsek daha iyi olacak: #305
