### ISSUE TITLE
Algolia API'a ait api-key'in gözükmesi

### ISSUE THREAD

**Issue by emirkabal** [ozgurg/vergihesaplayici.com#4]
API-KEY herkese açık bir şekilde gözüktüğü için kötü kullanıcılar tarafından yorulabilir.
![](https://i.emirkabal.com/OtZ13VLs.png)

**Comment by ozgurg** [comment]
Teşekkür ederim.
Şu anki keyi Algolia tarafından iptal ettim. Yeni bir key oluşturup siteyi beyaz listeye ekledim. Hala ön tarafta gözükecek ancak Algolia'dan cevap gelmeyecek.
