### ISSUE TITLE
Firebase?

### ISSUE THREAD

**Issue by ozgurkaracam** [ozgurg/vergihesaplayici.com#56]
Kolay gelsin projeyi inceledim temiz ve ogretici kod icin tesekkur ederim oncelikle. Firebase'i projeye ekleme nedeniniz nedir herhangi bir sunucu islemi gormedim production da. Merak ettim tesekkurler :)

**Comment by ozgurg** [comment]
Rica ederim, yardımcı olmasına sevindim.

Firebase'in Hosting servisini kullanarak barındırıyorum siteyi. https://firebase.google.com/docs/hosting
